config.reload.automatic: true
config.reload.interval: 3s
http.host: 0.0.0.0
log.level: info
path.config: /usr/share/logstash/pipeline
pipeline.batch.delay: 50
pipeline.batch.size: 125
pipeline.workers: 2
xpack.monitoring.enabled: false
